### ISSUE TITLE
calculateMoveParametersQueue

### ISSUE THREAD

**Issue by kinshuk-kotecha** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#11]
I don't understand the usage of calculateMoveParametersQueue, could you please elaborate? Thank you

**Comment by ArabelaTso** [comment]
You may regard it as a lock with the necessary information to make a decision on the next move. If this queue is empty, then the current piece thread should be waiting, otherwise, the piece thread should make a decision according to the given information. After the decision has been made, the queue should be cleared again and waiting for the information next round.

**Comment by kinshuk-kotecha** [comment]
For the getCandidateMove, the description says we have to pick one move from candidateMoveQueue. But won't the candidateMoveQueue only have one move everytime?

**Comment by Troublor** [comment]
Yes `candidateMoveQueue` only have one move every time, so just take the one from `candidateMoveQueue` and return as candidate move.

**Comment by kinshuk-kotecha** [comment]
in 'public synchronized Move getCandidateMove(Game game, Place source)' :
* so in this method, you need to pick up one candidate move from {@link Knight#candidateMoveQueue}
* - if the returned move is invalid, nothing should be returned.
* - Handle {@link InterruptedException}:
* - nothing should be returned in such case

How is it possible to return nothing for this function? Also shouldn't the move in candidateMoveQueue always be valid?

**Comment by Troublor** [comment]
You can return `null` to indicate that current thread does not proposed a piece. 
The piece thread can be `paused/terminated`, in which case no candidate move should be returned.
