### ISSUE TITLE
About test smart computer player

### ISSUE THREAD

**Issue by wilkinswu** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#34]
> For test smart behavior, the test will let Random Computer Player vs Smart Computer Player 5 times with the following configuration, if Smart Computer Player wins 3 or more times, the test is passed.

> - Board size: 15*15, protected steps 20, critical region size 5, critical capacity 2, random player plays first

"Board size: 15*15, protected steps 20, critical region size 5, critical capacity 2, random player plays first" is this the only configuration to be used in TA-only test for smart computer player?

**Comment by Troublor** [comment]
Yes

**Comment by kinshuk-kotecha** [comment]
So can we ignore the boardSize in generateSmartPieces(int boardSize, Player player) and directly use 15? In case we plan to assign specific behaviours to specific pieces?

**Comment by Troublor** [comment]
Actually, NO. You need to make it generalized to arbitrary board size.

**Comment by kinshuk-kotecha** [comment]
Can we add accessors and mutators for behaviour of a piece?

**Comment by Troublor** [comment]
Well, one workaround is to ensure your strategy is optimal when the game config is `Board size: 15*15, protected steps 20, critical region size 5, critical capacity 2, random player plays first`, while in other configs it may not smart enough. 

This is OK because the tests only let random player v.s. smart player at that config. 

But `generateSmartPieces` should always return a reasonable list of pieces (i.e. according to boardSize).

**Comment by Troublor** [comment]
> Can we add accessors and mutators for behaviour of a piece?

Yes you can.
