### ISSUE TITLE
The skeleton code doesn't pass the style checker

### ISSUE THREAD

**Issue by Kelvinluk827** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#39]
There is a static int variable `UNDO_LIMIT` in Game.class that is marked with the reason
`Name 'UNDO_LIMIT' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]`
The switch statement in ConsolePlayer.java is marked because
`switch without "default" clause. [MissingSwitchDefault]`
as well as other "unused" imports used in javadoc ironically

It is allowed to remove the javadoc for the stylechecker right, as well as the static int `UNDO_LIMIT`
However, I do not dare to modify the switch, feared of damaging the code. Is there a fix for that?

**Comment by Kwok-Kai-Yin-Pollux** [comment]
#30 the TA already answered it

**Comment by Troublor** [comment]
The reason why there are so many code style issues in skeleton code is that: skeleton code is adapted from TA implementation by deleting parts of the code. It is not complete code, so there is a lot of unused imports and other issues. 

Nevertheless, `UNDO_LIMIT` is indeed a problem since it should be camelCase and it's a mistake of TA.

**Comment by Kelvinluk827** [comment]
ok thx
